 spring:
  zipkin:
    base-url: http://localhost:9411/ # Zipkin server URL
  sleuth:
    sampler:
      probability: 1.0 # 100% tracing
    kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      acks: all
